services:

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile

    container_name: voice-backend

    env_file:
      - .env

    ports:
      - "8000:8000"

    depends_on:
      - db

    restart: unless-stopped

  db:
    image: postgres:16

    container_name: postgres-db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data:
